---
title: "Meeting Feb8"
author: "Noah Treutle"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(pomp)
#library(haitipkg)
library(doParallel)
library(doRNG)
load_all('/Users/hetankevin/Library/CloudStorage/OneDrive-Personal/Documents/UMich/Research/haitiRes/haitipkg')
knitr::opts_chunk$set(echo = TRUE)
```



### Setup pomp object

```{r pomp def}
mod_1 <- haiti1mod()
```

```{r test simulate}
# simulates from model1
# analogous to rnorm()
mod_1@params['betat'] = 1e-5
y <- simulate(mod_1)
plot(y)
```

0 -1606.361137
1e-1 -94347
1e-15 -1599.407524

```{r run levels}
# set run levels
run_level <- 2
Np <-          switch(run_level,100, 1e3, 5e3)
Nmif <-        switch(run_level, 11, 100, 200)
Nreps_eval <-  switch(run_level,  2,  10,  20)
Nreps_local <- switch(run_level, 11,  20,  40)
Nreps_global <-switch(run_level, 11,  20, 100)
Nsim <-        switch(run_level, 50, 100, 500) 
```


```{r windows compatibility}
# added to make compatible with windows
#dir.create("workflowtmp")
#options(pomp_cdir="workflowtmp")
#save(file=file.path("workflowtmp","pf1.rda"))
```


Need to find this file location
```{r}
#load("data/orig_mod/epi/epidemic_fit.rda")
```


-1609 0
-1609.986102 

```{r}
mod_1@params['betat'] = 1e-8
mod_lik = function(mod_1, Np){
  pf1 <- foreach(i=1:20,.packages="pomp",
      .export=c("mod_1","Np")) %dopar%
      pfilter(mod_1,Np=Np)
  L1 <- logmeanexp(sapply(pf1,logLik),se=TRUE)
  return(L1)
}
mod_lik(mod_1, Np)
mod_1@params

```

```{r}
# simulates the model and stores results in df called sims
simulate(mod_1,nsim=Nsim,seed=1643079359,
  format="data.frame",include.data=TRUE) -> sims
```




```{r}
# get param vals
mod_1@params %>% getElement('beta1')
getElement(mod_1@params, 'beta1')
mod_1@params[['beta1']]
```


```{r}

```


```{r}
mod_fit <- function(settings, out_dir, period, starts, full_mod) {
  #### make list of parameters being estimated
  if (period == 1) { ## endemic
    est_params <- c(paste0("beta", 1:6), "rho", "tau", "nu")
    rw_sds <- rw.sd(beta1 = 0.02, beta2 = 0.02, beta3 = 0.02,
                    beta4 = 0.02, beta5 = 0.02, beta6 = 0.02, #sig_sq = 0.02,
                    tau = 0.02, rho = 0.02, nu = 0.02)
    tstart <- 233
    tend <- 430
  } else if (period == 0) { ## epidemic
    est_params <- c(paste0("beta", 1:6), "rho", "tau", "nu", 
                    "E_0", "I_0")
    rw_sds <- rw.sd(beta1 = .02, beta2 = .02, beta3 = .02,
                    beta4 = .02, beta5 = .02, beta6 = .02,
                    tau = 0.02, rho = 0.02, nu = 0.02, #sig_sq = 0.02,
                    E_0 = ivp(0.2), I_0 = ivp(0.2))
    tstart <- 1
    tend <- 232
  } else {
    print("invalid period: must be 0 - epidemic or 1 - endemic")
    return()
  }
  
  bake(file = paste0(out_dir, "/iffits_", settings$str_if, ".rds"), 
       seed = settings$seed, {
         starts_if <- starts
         foreach(start = iter(starts_if, by = 'row'),
                 .combine = rbind, .inorder = FALSE,
                 .packages = c("pomp", "magrittr"),
                 .errorhandling = c('remove'),
                 .export = c("haiti.dat", "num_betas", "pop.haiti", 
                             "covartab", "settings"),
                 .noexport = c(),
                 .verbose = TRUE) %dopar% 
           {
             tic <- Sys.time()
             print(paste(start$parid, "iterated filtering"))
             po <- window(full_mod, start = tstart, end = tend)
             timezero(po) <- tstart - 1
             allpars <- c("rho","tau","beta1","beta2","beta3","beta4","beta5","beta6","betat",
                          "gamma","sigma","theta0","alpha","mu","delta","nu", #"sig_sq",
                          "S_0","E_0","I_0","A_0","R_0", "pop_0")
             coef(po) <- unlist(start[which(names(start) %in% allpars)])
             
             ## if no Exposed/Infectious, make it small but nonzero
             if (coef(po, "E_0") == 0.0 ) {
               coef(po, "E_0") <- 1e-9
             }
             if (coef(po, "I_0") == 0.0) {
               coef(po, "I_0") <- 1e-9
             }
             
             ## perform iterated filtering
             mf.mod <- mif2(po, Nmif = settings$nmif,
                            rw.sd = rw_sds,
                            Np = settings$nparticles,
                            cooling.type = "hyperbolic",
                            cooling.fraction.50 = 0.5,
                            verbose = FALSE)
             
             save(mf.mod, file = paste0(out_dir, "fitted_mod_", start$parid, ".rda"))
             
             ## get likelihood estimate 
             pf.lik <- replicate(10, pfilter(mf.mod, Np = settings$nparticles)) 
             ll <- sapply(pf.lik, logLik)
             ll <- logmeanexp(ll, se = TRUE)
             
             #if (!is.na(ll[1]) & ll[1] > -2000) { ## filter out extreme cases based on log-likelihood
               ## record mean effective sample size
               mean_ess <- vector(length = 10)
               for (i in 1:10) {
                 mean_ess[i] <- mean(pf.lik[[i]]@eff.sample.size)
               }
               
               toc <- Sys.time()
               etime <- toc-tic
               units(etime) <- "hours"
               
               ## simulate
               sims <- sim_data(po, pars = coef(mf.mod), 25)
               ## record simulations
               write_csv(sims, paste0(out_dir, "fitstates_if_", settings$str_if2, 
                                      "_parid", start$parid, "_seed",settings$seed, ".csv"))
               
               ## record parameter estimates
               dummy <- data.frame(model = paste0("if", period), 
                                   parid = start$parid,
                                   as.list(coef(mf.mod)),
                                   loglik = ll[1],
                                   loglik.se = ll[2],
                                   m_ess.min = min(mean_ess),
                                   m_ess.max = max(mean_ess),
                                   etime = as.numeric(etime))
               write_csv(dummy, paste0(out_dir, "parest_if_", settings$str_if2, 
                                       "_parid", start$parid, "_seed", 
                                       settings$seed, ".csv"))
               
               rm(fit_states, fit_states_sims, mf.mod, final_timept)
               gc()
               dummy
             #}
           }
       })  -> prof_if
  return(prof_if)
}
```



```{r}
rw_sd <- rw.sd(beta1 = .02, beta2 = .02, beta3 = .02,
                    beta4 = .02, beta5 = .02, beta6 = .02, betat=.02,
                    tau = 0.02, rho = 0.02, nu = 0.02, #sig_sq = 0.02,
                    E_0 = ivp(0.2), I_0 = ivp(0.2))


exl <- c("mod_1","Np","Nmif","rw_sd",
  "Nreps_local","Nreps_eval")


m2 <- foreach(i=1:Nreps_local,
    .packages="pomp",.combine=c,.export=exl) %dopar%
    mif2(mod_1, Np=Np, Nmif=Nmif, rw.sd=rw_sd,
         cooling.fraction.50=0.5)
```


```{r}
m2[[1]]@params
```

```{r}
mod_1@params
```
```{r}
mod_lik(m2[[1]], Np)
```

```{r}
box <- rbind(
  
)
```






```{r}
bake(file="results/box_eval1.rds",{
  registerDoRNG(833102018)
  foreach(i=1:Nreps_global,.packages="pomp",
    .combine=c) %dopar%
    mif2(m2[[1]],params=c(fixed_params,
      apply(box,1,function(x)runif(1,x[1],x[2]))))
},dependson=run_level) -> m3
bake(file="results/box_eval2.rds",{
  registerDoRNG(71449038)
  foreach(m=m3,.packages="pomp",
    .combine=rbind) %dopar%
    logmeanexp(replicate(Nreps_eval,
      logLik(pfilter(m,Np=Np))),se=TRUE)
},dependson=run_level) -> lik_m3
```


```{r}
sims = sims %>% mutate(N = S+E+I+A+R, 
                       beta = mod_1@params[['beta1']]*seas1 +
                         mod_1@params[['beta2']]*seas2 + 
                         mod_1@params[['beta3']]*seas3 + 
                         mod_1@params[['beta4']]*seas4 + 
                         mod_1@params[['beta5']]*seas5 + 
                         mod_1@params[['beta6']]*seas6)
(sims$I + (1-0.95)*sims$A)^mod_1@params[['nu']] * (sims$beta/sims$N) %>% plot()

sims
```


```{r}
sims = sims %>% mutate(N = S+E+I+A+R, 
                       beta = mod_1@params[['beta1']]*seas1 +
                         mod_1@params[['beta2']]*seas2 + 
                         mod_1@params[['beta3']]*seas3 + 
                         mod_1@params[['beta4']]*seas4 + 
                         mod_1@params[['beta5']]*seas5 + 
                         mod_1@params[['beta6']]*seas6)
(sims$I + (1-0.95)*sims$A)^mod_1@params[['nu']] * (sims$beta/sims$N) %>%
```








